call_assistant:
  fields:
    config_entry:
      required: true
      selector:
        config_entry:
          integration: assistant_conversation
    prompt:
      required: true
      selector:
        text:
          multiline: true
    